import type { MissionState } from "../types";
import { base64ToImageSrc } from "./imageUtils";
import { formatCoord, formatMs, formatPathLength, generateMissionId } from "./formatters";

export function exportPathAsJson(
  pathCoordinates: [number, number][],
  filename: string = "path_coordinates.json"
): void {
  const data = JSON.stringify(pathCoordinates, null, 2);
  const blob = new Blob([data], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportReportAsHtml(state: MissionState): void {
  const results = state.results;
  if (!results) return;

  const missionId = generateMissionId();
  const originalSrc = state.uploadedImageBase64
    ? base64ToImageSrc(state.uploadedImageBase64)
    : "";
  const segSrc = results.segmentation_mask_base64
    ? base64ToImageSrc(results.segmentation_mask_base64)
    : "";
  const resultSrc = results.result_image_base64
    ? base64ToImageSrc(results.result_image_base64)
    : "";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>PathFinder Report — ${missionId}</title>
<style>
  body{font-family:'Courier New',monospace;background:#0a0f1e;color:#e8eaf0;padding:40px;max-width:1200px;margin:0 auto}
  h1{color:#00e5ff;font-size:28px;letter-spacing:4px}
  h2{color:#00e5ff;font-size:18px;margin-top:30px;border-bottom:1px solid #1e2d4a;padding-bottom:8px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}
  .grid img{width:100%;border:1px solid #1e2d4a;border-radius:4px}
  table{width:100%;border-collapse:collapse;margin-top:16px}
  td,th{padding:10px 14px;border:1px solid #1e2d4a;text-align:left}
  th{background:#141d35;color:#00e5ff;text-transform:uppercase;font-size:12px;letter-spacing:2px}
  td{font-size:14px}
  .badge{display:inline-block;background:#00ff88;color:#0a0f1e;padding:2px 10px;border-radius:4px;font-size:12px;font-weight:bold}
</style>
</head>
<body>
<h1>PATHFINDER</h1>
<p>Mission ID: <strong>${missionId}</strong> <span class="badge">SUCCESS</span></p>
<h2>IMAGERY</h2>
<div class="grid">
  <div><p>Original</p><img src="${originalSrc}" alt="Original"/></div>
  <div><p>Segmentation</p><img src="${segSrc}" alt="Segmentation"/></div>
  <div><p>Result</p><img src="${resultSrc}" alt="Result"/></div>
</div>
<h2>ANALYSIS RESULTS</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Start Point</td><td>${formatCoord(results.start_point)}</td></tr>
  <tr><td>Rescue Target</td><td>${formatCoord(results.goal_point)}</td></tr>
  <tr><td>Path Length</td><td>${formatPathLength(results.path_length)}</td></tr>
  <tr><td>Avg Path Cost</td><td>${results.cost_map_stats.avg_path_cost.toFixed(2)}</td></tr>
  <tr><td>Min Cost</td><td>${results.cost_map_stats.min_cost.toFixed(2)}</td></tr>
  <tr><td>Max Cost</td><td>${results.cost_map_stats.max_cost.toFixed(2)}</td></tr>
  <tr><td>Processing Time</td><td>${formatMs(results.processing_time_ms)}</td></tr>
</table>
<p style="margin-top:40px;color:#8899bb;font-size:12px">Generated by PathFinder — AI-Powered Disaster Response System</p>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "pathfinder-report.html";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
